FROM smlsunxie/rudy-node:latest

RUN gem install compass
RUN gem install bootstrap-sass
RUN gem install sass

RUN npm install -g grunt-cli
RUN npm install -g bower
RUN npm install -g coffee-script
RUN npm install -g gulp
RUN npm install -g mocha
RUN npm install -g strongloop
